const translation = {
    source: {
        text01: "3 miles away from you",
        text02: "Are you over 18?",
        text03: "Our unfaithful girls only want entertainment. Can you be careful?",
        text04: "Do you agree to meetings without obligations??",
        text05: "The girls on this site are only interested in fun, not relationships. Do you agree with this condition?",
        text06: "Match",
        text07: "Your selections matched you with",
        text08: "of our cheating local girls",
        text09: "Chat with them!",
        text10: "No",
        text11: "Yes",
        text12: "What is your age?",
        text13: "Select your gender",
        text14: "I am a woman",
        text15: "I am a man",
        textCaptchaTitle: "Unlock the girl to move further",
    },
    en: {
        text01: "3 miles away from you",
        text02: "Are you over 18?",
        text03: "Our unfaithful girls only want entertainment. Can you be careful?",
        text04: "Do you agree to meetings without obligations??",
        text05: "The girls on this site are only interested in fun, not relationships. Do you agree with this condition?",
        text06: "Match",
        text07: "Your selections matched you with",
        text08: "of our cheating local girls",
        text09: "Chat with them!",
        text10: "No",
        text11: "Yes",
        text12: "What is your age?",
        text13: "Select your gender",
        text14: "I am a woman",
        text15: "I am a man",
        textCaptchaTitle: "Unlock the girl to move further",
    },
    de: {
        text01: "3 Meilen von Ihnen entfernt",
        text02: "Bist du über 18?",
        text03: "Unsere untreuen Mädchen wollen nur Unterhaltung. Kannst du aufpassen?",
        text04: "Stimmen Sie unverbindlichen Treffen zu??",
        text05: "Die Mädchen auf dieser Seite sind nur an Spaß interessiert, nicht an Beziehungen. Stimmen Sie dieser Bedingung zu?",
        text06: "Spiel",
        text07: "Ihre Auswahl stimmte mit",
        text08: "unserer betrügerischen Mädchen aus der Region überein",
        text09: "Chatte mit ihnen!",
        text10: "Nein",
        text11: "Ja",
        text12: "Was ist dein Alter?",
        text13: "Wähle dein Geschlecht",
        text14: "ich bin eine Frau",
        text15: "ich bin ein Mann",
        textCaptchaTitle: "Schalte das Mädchen frei, um weiter zu bewegen",
    },
    ja: {
        text01: "あなたから3マイル離れたところ",
        text02: "18才以上ですか？",
        text03: "私たちの不誠実な女の子は娯楽だけを望んでいます。気をつけてもらえますか？",
        text04: "義務のない会議に同意しますか？",
        text05: "このサイトの女の子は、人間関係ではなく、楽しみだけに興味があります。この条件に同意しますか？",
        text06: "一致",
        text07: "あなたの選択は私たちの浮気している地元の女の子の",
        text08: "とあなたを一致させました",
        text09: "彼らとチャットしよう！",
        text10: "番号",
        text11: "はい",
        text12: "あなたは何歳ですか？",
        text13: "性別を選んでください",
        text14: "私は女性です",
        text15: "私は男です",
        textCaptchaTitle: "さらに移動するには、女の子のロックを解除します",
    },
    sv: {
        text01: "3 miles från dig",
        text02: "Är du över 18?",
        text03: "Våra otrogna tjejer vill bara ha underhållning. Kan du vara försiktig?",
        text04: "Går ni med på möten utan förpliktelser??",
        text05: "Tjejerna på den här sidan är bara intresserade av roligt, inte relationer. Håller du med om detta villkor?",
        text06: "Match",
        text07: "Dina val matchade dig med",
        text08: "av våra fusk lokala tjejer",
        text09: "Chatta med dem!",
        text10: "Nej",
        text11: "Ja",
        text12: "Hur gammal är du?",
        text13: "Välj ditt kön",
        text14: "jag är en kvinna",
        text15: "jag är en man",
        textCaptchaTitle: "Lås upp flicken för att flytta längre",
    },
    da: {
        text01: "3 miles væk fra dig",
        text02: "Er du over 18?",
        text03: "Vores utro piger vil kun have underholdning. Kan du være forsigtig?",
        text04: "Indvilger du uforpligtende møder??",
        text05: "Pigerne på denne side er kun interesserede i sjov, ikke forhold. Er du enig i denne betingelse?",
        text06: "Match",
        text07: "Dine valg matchede dig medr",
        text08: "af vores snydende lokale pige",
        text09: "Chat med dem!",
        text10: "Ingen",
        text11: "Ja",
        text12: "Hvor gammel er du?",
        text13: "Vælg dit køn",
        text14: "Jeg er en kvinde",
        text15: "jeg er en mand",
        textCaptchaTitle: "Lås pigen op for at gå videre",
    },
    ar: {
        text01: "3 أميال منك",
        text02: "هل عمرك فوق 18؟",
        text03: "فتياتنا الخائنات لا يرغبن إلا في الترفيه. هل يمكنك ان تكون حذرا؟",
        text04: "هل توافق على اجتماعات بدون التزامات ؟؟",
        text05: "الفتيات في هذا الموقع يهتمن فقط بالمرح وليس بالعلاقات. هل توافق على هذا الشرط؟",
        text06: "مباراة",
        text07: "من فتياتنا المحليّات الغشّات",
        text08: "اختياراتك تطابقك مع",
        text09: "دردش معهم!",
        text10: "لا",
        text11: "نعم",
        text12: "ما هو عمرك؟",
        text13: "اختر جنسك",
        text14: "أنا إمراة",
        text15: "انا رجل",
        textCaptchaTitle: "افتح قفل الفتاة للتحرك لمسافة أبعد",
    },
    pt: {
        text01: "3 milhas de distância de você",
        text02: "Voce tem mais de 18 anos?",
        text03: "Nossas garotas infiéis só querem entretenimento. Você pode ter cuidado?",
        text04: "Você concorda com reuniões sem obrigações??",
        text05: "As garotas neste site estão interessadas apenas em diversão, não em relacionamentos. Você concorda com essa condição?",
        text06: "Combine",
        text07: "Suas seleções corresponderam a",
        text08: "de nossas garotas locais traidoras",
        text09: "Converse com eles!",
        text10: "Não",
        text11: "sim",
        text12: "Qual é a sua idade?",
        text13: "Selecione o seu sexo",
        text14: "Eu sou uma mulher",
        text15: "eu sou um homem",
        textCaptchaTitle: "Desbloqueie a garota para ir mais longe",
    },
    it: {
        text01: "3 miglia di distanza da te",
        text02: "Hai più di 18 anni?",
        text03: "Le nostre ragazze infedeli vogliono solo divertimento. Puoi stare attento?",
        text04: "Accetti incontri senza impegno??",
        text05: "Le ragazze su questo sito sono interessate solo al divertimento, non alle relazioni. Sei d'accordo con questa condizione?",
        text06: "Incontro",
        text07: "Le tue selezioni ti hanno abbinato all'",
        text08: "delle nostre ragazze locali che tradiscono",
        text09: "Chatta con loro!",
        text10: "No",
        text11: "sì",
        text12: "Quanti anni hai?",
        text13: "Seleziona il tuo sesso",
        text14: "Io sono una donna",
        text15: "sono un uomo",
        textCaptchaTitle: "Sblocca la ragazza per muoversi oltre",
    },
    zh: {
        text01: "离您3英里远",
        text02: "你超过18岁吗？",
        text03: "我们不忠的女孩只想要娱乐。你能小心点吗？",
        text04: "你同意没有义务的会议吗？",
        text05: "这个网站上的女孩只对乐趣感兴趣，而不是关系。你同意这个条件吗？",
        text06: "比赛",
        text07: "您的选择与",
        text08: "的当地作弊女孩相匹配",
        text09: "与他们聊天！",
        text10: "没有",
        text11: "是",
        text12: "你几岁？",
        text13: "选择您的性别",
        text14: "我是一个女人",
        text15: "我是一个男人",
        textCaptchaTitle: "解锁女孩走得更远",
    },
    es: {
        text01: "A 3 millas de ti",
        text02: "¿Eres mayor de 18 años?",
        text03: "Nuestras chicas infieles solo quieren entretenimiento. ¿Puedes tener cuidado?",
        text04: "¿Aceptas reuniones sin compromiso?",
        text05: "Las chicas de este sitio solo están interesadas en la diversión, no en las relaciones. ¿Estás de acuerdo con esta condición?",
        text06: "Partido",
        text07: "Tus selecciones te emparejaron con el",
        text08: "de nuestras chicas locales infieles",
        text09: "¡Charle con ellos!",
        text10: "No",
        text11: "si",
        text12: "¿Cuál es tu edad?",
        text13: "Selecciona tu género",
        text14: "soy una mujer",
        text15: "Yo soy un hombre",
        textCaptchaTitle: "Desbloquea a la niña para avanzar más lejos",
    },
    fr: {
        text01: "À 5 km de vous",
        text02: "As-tu plus de 18 ans?",
        text03: "Nos filles infidèles ne veulent que du divertissement. Pouvez-vous être prudent?",
        text04: "Acceptez-vous des rencontres sans obligations ??",
        text05: "Les filles sur ce site ne s'intéressent qu'au plaisir, pas aux relations. Êtes-vous d'accord avec cette condition ?",
        text06: "Rencontre",
        text07: "Vos sélections vous correspondaient avec",
        text08: "de nos filles locales infidèles",
        text09: "Discutez avec eux!",
        text10: "Non",
        text11: "Oui",
        text12: "Quel âge avez-vous?",
        text13: "Sélectionnez votre sexe",
        text14: "Je suis une femme",
        text15: "je suis un homme",
        textCaptchaTitle: "Déverrouillez la fille pour aller plus loin",
    },
    nl: {
        text01: "3 mijl bij je vandaan",
        text02: "Ben jij ouder dan 18?",
        text03: "Onze ontrouwe meisjes willen alleen entertainment. Kun je voorzichtig zijn?",
        text04: "Gaat u akkoord met vrijblijvende bijeenkomsten??",
        text05: "De meisjes op deze site zijn alleen geïnteresseerd in plezier, niet in relaties. Gaat u akkoord met deze voorwaarde?",
        text06: "Bij elkaar passen",
        text07: "Uw selecties kwamen overeen met",
        text08: "van onze vreemdgaande lokale meisjes",
        text09: "Chat met ze!",
        text10: "Nee",
        text11: "Ja",
        text12: "Hoe oud ben jij?",
        text13: "Kies je geslacht",
        text14: "ik ben een vrouw",
        text15: "ik ben een man",
        textCaptchaTitle: "Ontgrendel het meisje om verder te bewegen",
    },
    ru: {
        text01: "В 3 км от вас",
        text02: "Вам больше 18?",
        text03: "Нашим неверным девушкам нужны только развлечения. Вы можете быть осторожным?",
        text04: "Вы согласны к встречам без обязательств??",
        text05: "Девушек на этом сайте интересует только веселье, а не отношения. Вы согласны с этим условием?",
        text06: "Соответствие",
        text07: "По вашему выбору вам подошли",
        text08: "наших неверных местных девушек.",
        text09: "Пообщайтесь с ними!",
        text10: "Нет",
        text11: "да",
        text12: "Сколько вам лет?",
        text13: "Выберите свой пол",
        text14: "Я женщина",
        text15: "Я мужчина",
        textCaptchaTitle: "Разблокируйте девушку, чтобы продолжить",
    },
    uk: {
        text01: "3 км від вас",
        text02: "Вам більше 18?",
        text03: "Нашим невірним дівчатам потрібні лише розваги. Ви можете бути обережним?",
        text04: "Ви згодні до зустрічей без зобов'язань?",
        text05: "Дівчат на цьому сайті цікавить лише веселощі, а не стосунки. Ви погоджуєтесь з цією умовою?",
        text06: "Відповідність",
        text07: "За вашим вибором вам підійшли",
        text08: "наших невірних місцевих дівчат.",
        text09: "Побалакайте з ними!",
        text10: "Ні",
        text11: "Так",
        text12: "Скільки вам років?",
        text13: "Виберіть стать",
        text14: "Я жінка",
        text15: "Я чоловік",
        textCaptchaTitle: "Розблокуйте дівчину, щоб продовжити",
    },
};

function detect_language() {
    var userLang =
        (navigator.languages && navigator.languages[0]) ||
        navigator.language ||
        navigator.userLanguage;
    if (userLang == "zh-CN" || userLang == "zh-SG" || userLang == "zh-MY" || userLang == "zh-CHS") {
        userLang = "zh";
    } else if (
        userLang == "zh-HK" ||
        userLang == "zh-MO" ||
        userLang == "zh-TW" ||
        userLang == "zh-CHT"
    ) {
        userLang = "zh";
    } else if (userLang.length > 2) {
        userLang = userLang[0] + userLang[1];
    }
    return userLang;
}
$(function() {
    let browserLang = detect_language();
    const langTranslation =
        translation[browserLang] && Object.keys(translation[browserLang]).length > 0 ?
        translation[browserLang] :
        translation["source"];
    for (const textKey of Object.keys(langTranslation)) {
        const textString = langTranslation[textKey];
        if (textKey === "title") {
            $(textKey).text(textString);
        } else {
            $(`.${textKey}
             `).text(textString);
        }
    }
});